extern "C" {
    fn strlen(__s: *const core::ffi::c_char) -> size_t;
}
pub type size_t = usize;
pub type uchar = core::ffi::c_uchar;
#[no_mangle]
pub static mut lowervec: [core::ffi::c_uchar; 256] = [
    0 as core::ffi::c_int as core::ffi::c_uchar,
    1 as core::ffi::c_int as core::ffi::c_uchar,
    2 as core::ffi::c_int as core::ffi::c_uchar,
    3 as core::ffi::c_int as core::ffi::c_uchar,
    4 as core::ffi::c_int as core::ffi::c_uchar,
    5 as core::ffi::c_int as core::ffi::c_uchar,
    6 as core::ffi::c_int as core::ffi::c_uchar,
    7 as core::ffi::c_int as core::ffi::c_uchar,
    8 as core::ffi::c_int as core::ffi::c_uchar,
    9 as core::ffi::c_int as core::ffi::c_uchar,
    10 as core::ffi::c_int as core::ffi::c_uchar,
    11 as core::ffi::c_int as core::ffi::c_uchar,
    12 as core::ffi::c_int as core::ffi::c_uchar,
    13 as core::ffi::c_int as core::ffi::c_uchar,
    14 as core::ffi::c_int as core::ffi::c_uchar,
    15 as core::ffi::c_int as core::ffi::c_uchar,
    16 as core::ffi::c_int as core::ffi::c_uchar,
    17 as core::ffi::c_int as core::ffi::c_uchar,
    18 as core::ffi::c_int as core::ffi::c_uchar,
    19 as core::ffi::c_int as core::ffi::c_uchar,
    20 as core::ffi::c_int as core::ffi::c_uchar,
    21 as core::ffi::c_int as core::ffi::c_uchar,
    22 as core::ffi::c_int as core::ffi::c_uchar,
    23 as core::ffi::c_int as core::ffi::c_uchar,
    24 as core::ffi::c_int as core::ffi::c_uchar,
    25 as core::ffi::c_int as core::ffi::c_uchar,
    26 as core::ffi::c_int as core::ffi::c_uchar,
    27 as core::ffi::c_int as core::ffi::c_uchar,
    28 as core::ffi::c_int as core::ffi::c_uchar,
    29 as core::ffi::c_int as core::ffi::c_uchar,
    30 as core::ffi::c_int as core::ffi::c_uchar,
    31 as core::ffi::c_int as core::ffi::c_uchar,
    32 as core::ffi::c_int as core::ffi::c_uchar,
    '!' as i32 as core::ffi::c_uchar,
    '"' as i32 as core::ffi::c_uchar,
    '#' as i32 as core::ffi::c_uchar,
    '$' as i32 as core::ffi::c_uchar,
    '%' as i32 as core::ffi::c_uchar,
    '&' as i32 as core::ffi::c_uchar,
    '\'' as i32 as core::ffi::c_uchar,
    '(' as i32 as core::ffi::c_uchar,
    ')' as i32 as core::ffi::c_uchar,
    '*' as i32 as core::ffi::c_uchar,
    '+' as i32 as core::ffi::c_uchar,
    ',' as i32 as core::ffi::c_uchar,
    '-' as i32 as core::ffi::c_uchar,
    '.' as i32 as core::ffi::c_uchar,
    '/' as i32 as core::ffi::c_uchar,
    '0' as i32 as core::ffi::c_uchar,
    '1' as i32 as core::ffi::c_uchar,
    '2' as i32 as core::ffi::c_uchar,
    '3' as i32 as core::ffi::c_uchar,
    '4' as i32 as core::ffi::c_uchar,
    '5' as i32 as core::ffi::c_uchar,
    '6' as i32 as core::ffi::c_uchar,
    '7' as i32 as core::ffi::c_uchar,
    '8' as i32 as core::ffi::c_uchar,
    '9' as i32 as core::ffi::c_uchar,
    ':' as i32 as core::ffi::c_uchar,
    ';' as i32 as core::ffi::c_uchar,
    '<' as i32 as core::ffi::c_uchar,
    '=' as i32 as core::ffi::c_uchar,
    '>' as i32 as core::ffi::c_uchar,
    '?' as i32 as core::ffi::c_uchar,
    '@' as i32 as core::ffi::c_uchar,
    'a' as i32 as core::ffi::c_uchar,
    'b' as i32 as core::ffi::c_uchar,
    'c' as i32 as core::ffi::c_uchar,
    'd' as i32 as core::ffi::c_uchar,
    'e' as i32 as core::ffi::c_uchar,
    'f' as i32 as core::ffi::c_uchar,
    'g' as i32 as core::ffi::c_uchar,
    'h' as i32 as core::ffi::c_uchar,
    'i' as i32 as core::ffi::c_uchar,
    'j' as i32 as core::ffi::c_uchar,
    'k' as i32 as core::ffi::c_uchar,
    'l' as i32 as core::ffi::c_uchar,
    'm' as i32 as core::ffi::c_uchar,
    'n' as i32 as core::ffi::c_uchar,
    'o' as i32 as core::ffi::c_uchar,
    'p' as i32 as core::ffi::c_uchar,
    'q' as i32 as core::ffi::c_uchar,
    'r' as i32 as core::ffi::c_uchar,
    's' as i32 as core::ffi::c_uchar,
    't' as i32 as core::ffi::c_uchar,
    'u' as i32 as core::ffi::c_uchar,
    'v' as i32 as core::ffi::c_uchar,
    'w' as i32 as core::ffi::c_uchar,
    'x' as i32 as core::ffi::c_uchar,
    'y' as i32 as core::ffi::c_uchar,
    'z' as i32 as core::ffi::c_uchar,
    '[' as i32 as core::ffi::c_uchar,
    '\\' as i32 as core::ffi::c_uchar,
    ']' as i32 as core::ffi::c_uchar,
    '^' as i32 as core::ffi::c_uchar,
    '_' as i32 as core::ffi::c_uchar,
    '`' as i32 as core::ffi::c_uchar,
    'a' as i32 as core::ffi::c_uchar,
    'b' as i32 as core::ffi::c_uchar,
    'c' as i32 as core::ffi::c_uchar,
    'd' as i32 as core::ffi::c_uchar,
    'e' as i32 as core::ffi::c_uchar,
    'f' as i32 as core::ffi::c_uchar,
    'g' as i32 as core::ffi::c_uchar,
    'h' as i32 as core::ffi::c_uchar,
    'i' as i32 as core::ffi::c_uchar,
    'j' as i32 as core::ffi::c_uchar,
    'k' as i32 as core::ffi::c_uchar,
    'l' as i32 as core::ffi::c_uchar,
    'm' as i32 as core::ffi::c_uchar,
    'n' as i32 as core::ffi::c_uchar,
    'o' as i32 as core::ffi::c_uchar,
    'p' as i32 as core::ffi::c_uchar,
    'q' as i32 as core::ffi::c_uchar,
    'r' as i32 as core::ffi::c_uchar,
    's' as i32 as core::ffi::c_uchar,
    't' as i32 as core::ffi::c_uchar,
    'u' as i32 as core::ffi::c_uchar,
    'v' as i32 as core::ffi::c_uchar,
    'w' as i32 as core::ffi::c_uchar,
    'x' as i32 as core::ffi::c_uchar,
    'y' as i32 as core::ffi::c_uchar,
    'z' as i32 as core::ffi::c_uchar,
    '{' as i32 as core::ffi::c_uchar,
    '|' as i32 as core::ffi::c_uchar,
    '}' as i32 as core::ffi::c_uchar,
    '~' as i32 as core::ffi::c_uchar,
    127 as core::ffi::c_int as core::ffi::c_uchar,
    'c' as i32 as core::ffi::c_uchar,
    'u' as i32 as core::ffi::c_uchar,
    'e' as i32 as core::ffi::c_uchar,
    'a' as i32 as core::ffi::c_uchar,
    'a' as i32 as core::ffi::c_uchar,
    'a' as i32 as core::ffi::c_uchar,
    'a' as i32 as core::ffi::c_uchar,
    'c' as i32 as core::ffi::c_uchar,
    'e' as i32 as core::ffi::c_uchar,
    'e' as i32 as core::ffi::c_uchar,
    'e' as i32 as core::ffi::c_uchar,
    'i' as i32 as core::ffi::c_uchar,
    'i' as i32 as core::ffi::c_uchar,
    'i' as i32 as core::ffi::c_uchar,
    'a' as i32 as core::ffi::c_uchar,
    'a' as i32 as core::ffi::c_uchar,
    'e' as i32 as core::ffi::c_uchar,
    145 as core::ffi::c_int as core::ffi::c_uchar,
    146 as core::ffi::c_int as core::ffi::c_uchar,
    'o' as i32 as core::ffi::c_uchar,
    'o' as i32 as core::ffi::c_uchar,
    'o' as i32 as core::ffi::c_uchar,
    'u' as i32 as core::ffi::c_uchar,
    'u' as i32 as core::ffi::c_uchar,
    'y' as i32 as core::ffi::c_uchar,
    'o' as i32 as core::ffi::c_uchar,
    'u' as i32 as core::ffi::c_uchar,
    155 as core::ffi::c_int as core::ffi::c_uchar,
    156 as core::ffi::c_int as core::ffi::c_uchar,
    157 as core::ffi::c_int as core::ffi::c_uchar,
    158 as core::ffi::c_int as core::ffi::c_uchar,
    159 as core::ffi::c_int as core::ffi::c_uchar,
    'a' as i32 as core::ffi::c_uchar,
    'i' as i32 as core::ffi::c_uchar,
    'o' as i32 as core::ffi::c_uchar,
    'u' as i32 as core::ffi::c_uchar,
    'n' as i32 as core::ffi::c_uchar,
    'n' as i32 as core::ffi::c_uchar,
    166 as core::ffi::c_int as core::ffi::c_uchar,
    167 as core::ffi::c_int as core::ffi::c_uchar,
    168 as core::ffi::c_int as core::ffi::c_uchar,
    169 as core::ffi::c_int as core::ffi::c_uchar,
    170 as core::ffi::c_int as core::ffi::c_uchar,
    171 as core::ffi::c_int as core::ffi::c_uchar,
    172 as core::ffi::c_int as core::ffi::c_uchar,
    173 as core::ffi::c_int as core::ffi::c_uchar,
    174 as core::ffi::c_int as core::ffi::c_uchar,
    175 as core::ffi::c_int as core::ffi::c_uchar,
    176 as core::ffi::c_int as core::ffi::c_uchar,
    177 as core::ffi::c_int as core::ffi::c_uchar,
    178 as core::ffi::c_int as core::ffi::c_uchar,
    179 as core::ffi::c_int as core::ffi::c_uchar,
    180 as core::ffi::c_int as core::ffi::c_uchar,
    181 as core::ffi::c_int as core::ffi::c_uchar,
    182 as core::ffi::c_int as core::ffi::c_uchar,
    183 as core::ffi::c_int as core::ffi::c_uchar,
    184 as core::ffi::c_int as core::ffi::c_uchar,
    185 as core::ffi::c_int as core::ffi::c_uchar,
    186 as core::ffi::c_int as core::ffi::c_uchar,
    187 as core::ffi::c_int as core::ffi::c_uchar,
    188 as core::ffi::c_int as core::ffi::c_uchar,
    189 as core::ffi::c_int as core::ffi::c_uchar,
    190 as core::ffi::c_int as core::ffi::c_uchar,
    191 as core::ffi::c_int as core::ffi::c_uchar,
    192 as core::ffi::c_int as core::ffi::c_uchar,
    193 as core::ffi::c_int as core::ffi::c_uchar,
    194 as core::ffi::c_int as core::ffi::c_uchar,
    195 as core::ffi::c_int as core::ffi::c_uchar,
    196 as core::ffi::c_int as core::ffi::c_uchar,
    197 as core::ffi::c_int as core::ffi::c_uchar,
    198 as core::ffi::c_int as core::ffi::c_uchar,
    199 as core::ffi::c_int as core::ffi::c_uchar,
    200 as core::ffi::c_int as core::ffi::c_uchar,
    201 as core::ffi::c_int as core::ffi::c_uchar,
    202 as core::ffi::c_int as core::ffi::c_uchar,
    203 as core::ffi::c_int as core::ffi::c_uchar,
    204 as core::ffi::c_int as core::ffi::c_uchar,
    205 as core::ffi::c_int as core::ffi::c_uchar,
    206 as core::ffi::c_int as core::ffi::c_uchar,
    207 as core::ffi::c_int as core::ffi::c_uchar,
    208 as core::ffi::c_int as core::ffi::c_uchar,
    209 as core::ffi::c_int as core::ffi::c_uchar,
    210 as core::ffi::c_int as core::ffi::c_uchar,
    211 as core::ffi::c_int as core::ffi::c_uchar,
    212 as core::ffi::c_int as core::ffi::c_uchar,
    213 as core::ffi::c_int as core::ffi::c_uchar,
    214 as core::ffi::c_int as core::ffi::c_uchar,
    215 as core::ffi::c_int as core::ffi::c_uchar,
    216 as core::ffi::c_int as core::ffi::c_uchar,
    217 as core::ffi::c_int as core::ffi::c_uchar,
    218 as core::ffi::c_int as core::ffi::c_uchar,
    219 as core::ffi::c_int as core::ffi::c_uchar,
    220 as core::ffi::c_int as core::ffi::c_uchar,
    221 as core::ffi::c_int as core::ffi::c_uchar,
    222 as core::ffi::c_int as core::ffi::c_uchar,
    223 as core::ffi::c_int as core::ffi::c_uchar,
    224 as core::ffi::c_int as core::ffi::c_uchar,
    225 as core::ffi::c_int as core::ffi::c_uchar,
    226 as core::ffi::c_int as core::ffi::c_uchar,
    227 as core::ffi::c_int as core::ffi::c_uchar,
    228 as core::ffi::c_int as core::ffi::c_uchar,
    229 as core::ffi::c_int as core::ffi::c_uchar,
    230 as core::ffi::c_int as core::ffi::c_uchar,
    231 as core::ffi::c_int as core::ffi::c_uchar,
    232 as core::ffi::c_int as core::ffi::c_uchar,
    233 as core::ffi::c_int as core::ffi::c_uchar,
    234 as core::ffi::c_int as core::ffi::c_uchar,
    235 as core::ffi::c_int as core::ffi::c_uchar,
    236 as core::ffi::c_int as core::ffi::c_uchar,
    237 as core::ffi::c_int as core::ffi::c_uchar,
    238 as core::ffi::c_int as core::ffi::c_uchar,
    239 as core::ffi::c_int as core::ffi::c_uchar,
    240 as core::ffi::c_int as core::ffi::c_uchar,
    241 as core::ffi::c_int as core::ffi::c_uchar,
    242 as core::ffi::c_int as core::ffi::c_uchar,
    243 as core::ffi::c_int as core::ffi::c_uchar,
    244 as core::ffi::c_int as core::ffi::c_uchar,
    245 as core::ffi::c_int as core::ffi::c_uchar,
    246 as core::ffi::c_int as core::ffi::c_uchar,
    247 as core::ffi::c_int as core::ffi::c_uchar,
    248 as core::ffi::c_int as core::ffi::c_uchar,
    249 as core::ffi::c_int as core::ffi::c_uchar,
    250 as core::ffi::c_int as core::ffi::c_uchar,
    251 as core::ffi::c_int as core::ffi::c_uchar,
    252 as core::ffi::c_int as core::ffi::c_uchar,
    253 as core::ffi::c_int as core::ffi::c_uchar,
    254 as core::ffi::c_int as core::ffi::c_uchar,
    255 as core::ffi::c_int as core::ffi::c_uchar,
];
pub const LARGE: core::ffi::c_int = 32767 as core::ffi::c_int;
static mut patlen: core::ffi::c_int = 0;
static mut skip: [core::ffi::c_int; 256] = [0; 256];
static mut skip2: core::ffi::c_int = 0;
static mut pat: *mut uchar = 0 as *const uchar as *mut uchar;
#[no_mangle]
pub unsafe extern "C" fn bmha_init(mut pattern: *const core::ffi::c_char) {
    let mut i: core::ffi::c_int = 0;
    let mut j: core::ffi::c_int = 0;
    pat = pattern as *mut uchar;
    patlen = strlen(pattern) as core::ffi::c_int;
    i = 0 as core::ffi::c_int;
    while i <= UCHAR_MAX {
        skip[i as usize] = patlen;
        j = patlen - 1 as core::ffi::c_int;
        while j >= 0 as core::ffi::c_int {
            if lowervec[i as uchar as usize] as core::ffi::c_int
                == lowervec[*pat.offset(j as isize) as usize] as core::ffi::c_int
            {
                break;
            }
            j -= 1;
        }
        if j >= 0 as core::ffi::c_int {
            skip[i as usize] = patlen - j - 1 as core::ffi::c_int;
        }
        if j == patlen - 1 as core::ffi::c_int {
            skip[i as usize] = LARGE;
        }
        i += 1;
    }
    skip2 = patlen;
    i = 0 as core::ffi::c_int;
    while i < patlen - 1 as core::ffi::c_int {
        if lowervec[*pat.offset(i as isize) as usize] as core::ffi::c_int
            == lowervec[*pat.offset((patlen - 1 as core::ffi::c_int) as isize) as usize]
                as core::ffi::c_int
        {
            skip2 = patlen - i - 1 as core::ffi::c_int;
        }
        i += 1;
    }
}