#[derive(Copy, Clone)]
#[repr(C)]
pub union C2RustUnnamed {
    pub ch: [core::ffi::c_uchar; 4],
    pub y: core::ffi::c_long,
}
static mut bits: [core::ffi::c_char; 256] = [
    0 as core::ffi::c_int as core::ffi::c_char,
    1 as core::ffi::c_int as core::ffi::c_char,
    1 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    1 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    1 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    1 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    1 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    1 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    7 as core::ffi::c_int as core::ffi::c_char,
    1 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    7 as core::ffi::c_int as core::ffi::c_char,
    2 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    7 as core::ffi::c_int as core::ffi::c_char,
    3 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    7 as core::ffi::c_int as core::ffi::c_char,
    4 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    7 as core::ffi::c_int as core::ffi::c_char,
    5 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    7 as core::ffi::c_int as core::ffi::c_char,
    6 as core::ffi::c_int as core::ffi::c_char,
    7 as core::ffi::c_int as core::ffi::c_char,
    7 as core::ffi::c_int as core::ffi::c_char,
    8 as core::ffi::c_int as core::ffi::c_char,
];
#[no_mangle]
pub unsafe extern "C" fn ntbl_bitcount(mut x: core::ffi::c_long) -> core::ffi::c_int {
    return bits[(x as core::ffi::c_ulong & 0xf as core::ffi::c_ulong) as core::ffi::c_int
        as usize] as core::ffi::c_int
        + bits[((x as core::ffi::c_ulong & 0xf0 as core::ffi::c_ulong)
            >> 4 as core::ffi::c_int) as core::ffi::c_int as usize] as core::ffi::c_int
        + bits[((x as core::ffi::c_ulong & 0xf00 as core::ffi::c_ulong)
            >> 8 as core::ffi::c_int) as core::ffi::c_int as usize] as core::ffi::c_int
        + bits[((x as core::ffi::c_ulong & 0xf000 as core::ffi::c_ulong)
            >> 12 as core::ffi::c_int) as core::ffi::c_int as usize] as core::ffi::c_int
        + bits[((x as core::ffi::c_ulong & 0xf0000 as core::ffi::c_ulong)
            >> 16 as core::ffi::c_int) as core::ffi::c_int as usize] as core::ffi::c_int
        + bits[((x as core::ffi::c_ulong & 0xf00000 as core::ffi::c_ulong)
            >> 20 as core::ffi::c_int) as core::ffi::c_int as usize] as core::ffi::c_int
        + bits[((x as core::ffi::c_ulong & 0xf000000 as core::ffi::c_ulong)
            >> 24 as core::ffi::c_int) as core::ffi::c_int as usize] as core::ffi::c_int
        + bits[((x as core::ffi::c_ulong & 0xf0000000 as core::ffi::c_ulong)
            >> 28 as core::ffi::c_int) as core::ffi::c_int as usize] as core::ffi::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn BW_btbl_bitcount(mut x: core::ffi::c_long) -> core::ffi::c_int {
    let mut U: C2RustUnnamed = C2RustUnnamed { ch: [0; 4] };
    U.y = x;
    return bits[U.ch[0 as usize] as usize] as core::ffi::c_int
        + bits[U.ch[1 as usize] as usize] as core::ffi::c_int
        + bits[U.ch[3 as usize] as usize] as core::ffi::c_int
        + bits[U.ch[2 as usize] as usize] as core::ffi::c_int;
}
#[no_mangle]
pub unsafe extern "C" fn AR_btbl_bitcount(mut x: core::ffi::c_long) -> core::ffi::c_int {
    let mut Ptr: *mut core::ffi::c_uchar = &mut x as *mut core::ffi::c_long as *mut core::ffi::c_uchar;
    let mut Accu: core::ffi::c_int = 0;

    unsafe {
        for _ in 0..4 {
            Accu += bits[*Ptr as usize] as core::ffi::c_int;
            Ptr = Ptr.offset(1);
        }
    }

    return Accu;
}